# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'convert_v01.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 1041)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.select_btn = QtWidgets.QPushButton(self.centralwidget)
        self.select_btn.setObjectName("select_btn")
        self.verticalLayout.addWidget(self.select_btn)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.groupBox_create_new_sequence = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_create_new_sequence.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_create_new_sequence.sizePolicy().hasHeightForWidth())
        self.groupBox_create_new_sequence.setSizePolicy(sizePolicy)
        self.groupBox_create_new_sequence.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_create_new_sequence.setObjectName("groupBox_create_new_sequence")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_create_new_sequence)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.create_sequence_btn = QtWidgets.QPushButton(self.groupBox_create_new_sequence)
        self.create_sequence_btn.setMinimumSize(QtCore.QSize(45, 45))
        self.create_sequence_btn.setMaximumSize(QtCore.QSize(45, 45))
        self.create_sequence_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("N:/Downloads/gallery.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.create_sequence_btn.setIcon(icon)
        self.create_sequence_btn.setIconSize(QtCore.QSize(30, 30))
        self.create_sequence_btn.setObjectName("create_sequence_btn")
        self.horizontalLayout.addWidget(self.create_sequence_btn)
        self.radioButton_jpg = QtWidgets.QRadioButton(self.groupBox_create_new_sequence)
        self.radioButton_jpg.setMaximumSize(QtCore.QSize(100, 16777215))
        self.radioButton_jpg.setObjectName("radioButton_jpg")
        self.horizontalLayout.addWidget(self.radioButton_jpg)
        self.radioButton_png = QtWidgets.QRadioButton(self.groupBox_create_new_sequence)
        self.radioButton_png.setObjectName("radioButton_png")
        self.horizontalLayout.addWidget(self.radioButton_png)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addWidget(self.groupBox_create_new_sequence)
        self.groupBox_generate_screenshots = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_generate_screenshots.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_generate_screenshots.setObjectName("groupBox_generate_screenshots")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_generate_screenshots)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.screenshots_btn = QtWidgets.QPushButton(self.groupBox_generate_screenshots)
        self.screenshots_btn.setMinimumSize(QtCore.QSize(45, 45))
        self.screenshots_btn.setMaximumSize(QtCore.QSize(45, 45))
        self.screenshots_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("N:/Downloads/scissors.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.screenshots_btn.setIcon(icon1)
        self.screenshots_btn.setIconSize(QtCore.QSize(30, 30))
        self.screenshots_btn.setObjectName("screenshots_btn")
        self.horizontalLayout_8.addWidget(self.screenshots_btn)
        self.label_7 = QtWidgets.QLabel(self.groupBox_generate_screenshots)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        self.label_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.screenshot_frames = QtWidgets.QLineEdit(self.groupBox_generate_screenshots)
        self.screenshot_frames.setText("")
        self.screenshot_frames.setObjectName("screenshot_frames")
        self.horizontalLayout_8.addWidget(self.screenshot_frames)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_8.addLayout(self.horizontalLayout_19)
        self.verticalLayout.addWidget(self.groupBox_generate_screenshots)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton.setMaximumSize(QtCore.QSize(45, 45))
        self.pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("N:/Downloads/add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_9.addWidget(self.pushButton)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_11.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_11.addWidget(self.radioButton_2)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_11)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_2.setMaximumSize(QtCore.QSize(45, 45))
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("N:/Downloads/video-conference.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_12.addWidget(self.pushButton_2)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_16.addWidget(self.label_9)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_16)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_3.setMaximumSize(QtCore.QSize(45, 45))
        self.pushButton_3.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("N:/Downloads/video.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon4)
        self.pushButton_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_13.addWidget(self.pushButton_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(160, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_4.setMaximumSize(QtCore.QSize(45, 45))
        self.pushButton_4.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("N:/Downloads/video-editing.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon5)
        self.pushButton_4.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_14.addWidget(self.pushButton_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_5.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_5.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_5.setMaximumSize(QtCore.QSize(45, 45))
        self.pushButton_5.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("N:/Downloads/rotation.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon6)
        self.pushButton_5.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_15.addWidget(self.label_8)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_15.addWidget(self.lineEdit_3)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_15)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 722, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.select_btn.setText(_translate("MainWindow", "Select a video file to process"))
        self.label_2.setText(_translate("MainWindow", "Selected Video source:"))
        self.label.setText(_translate("MainWindow", "..."))
        self.groupBox_create_new_sequence.setTitle(_translate("MainWindow", "Convert to an image sequence"))
        self.radioButton_jpg.setText(_translate("MainWindow", "JPG sequence"))
        self.radioButton_png.setText(_translate("MainWindow", "PNG sequence"))
        self.groupBox_generate_screenshots.setTitle(_translate("MainWindow", "Generate screenshots / Extract frames"))
        self.label_7.setText(_translate("MainWindow", "Screenshot frames"))
        self.groupBox.setTitle(_translate("MainWindow", "Extract audio data from your video"))
        self.radioButton.setText(_translate("MainWindow", "MP3"))
        self.radioButton_2.setText(_translate("MainWindow", "WAV"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Extract a SRT (subtitle) file from your video"))
        self.label_9.setText(_translate("MainWindow", "Download embedded SRT data"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Convert to another codec"))
        self.label_3.setText(_translate("MainWindow", "Select a codec to convert to:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "mp4"))
        self.comboBox.setItemText(1, _translate("MainWindow", "mov"))
        self.comboBox.setItemText(2, _translate("MainWindow", "avi"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Extract a snippet/part of your video"))
        self.label_4.setText(_translate("MainWindow", "Start Frame:"))
        self.label_5.setText(_translate("MainWindow", "Duration (in frames):"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Loop your video"))
        self.label_8.setText(_translate("MainWindow", "How many loops?"))
        self.label_6.setText(_translate("MainWindow", "Video Data Analysis:"))
